name: 'AWS IaC using Terraform'

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Action
      - name: Terraform Action
        run: |
          case ${{ github.event.inputs.action }} in
            plan)
              terraform plan
              ;;
            apply)
              terraform apply -auto-approve
              ;;
            destroy)
              terraform destroy -auto-approve
              ;;
            *)
              echo "Invalid action: ${{ github.event.inputs.action }}"
              exit 1
              ;;
          esac
