name: 'AWS IaC using Terraform'

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials set."

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan by default or execute user-chosen action
      - name: Terraform Action
        run: |
          case ${{ github.event.inputs.action || 'plan' }} in
            plan)
              echo "Running Terraform Plan..."
              terraform plan
              ;;
            apply)
              echo "Running Terraform Apply..."
              terraform apply -auto-approve
              ;;
            destroy)
              echo "Running Terraform Destroy..."
              terraform destroy -auto-approve
              ;;
            *)
              echo "Invalid action: ${{ github.event.inputs.action }}"
              exit 1
              ;;
          esac
